### ISSUE TITLE
Config errors with input_select after hass.io upgrade to 0.92

### ISSUE THREAD

**Issue by DrFrankReade** [TonyApuzzo/home-assistant-config#1]
Config checker produces the following message after upgrading HASS.IO to 0.92.0

Integration not found: introduction
Invalid config for [input_select]: [values] is an invalid option for [input_select]. Check: input_select->input_select->openevse_service_level->values. (See ?, line ?). Please check the docs at https://home-assistant.io/components/input_select/

**Comment by TonyApuzzo** [comment]
Duly noted -- the new service integrations approach requires moving and renaming files for the custom components to load correctly.

**Comment by TonyApuzzo** [comment]
I've migrated my custom components to the new servicing model: https://github.com/TonyApuzzo/home-assistant-config/tree/master/custom_components/
